language: php

php:
  - 5.3
  - 5.4

env:
  - DB=mysql DB_USER=root

before_script:
  # MySQL
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'DROP DATABASE IF EXISTS test; '; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE test'; fi"

script:
  - cd test; phpunit Tests;