language: php

php:
  - 5.3
  - 5.4

env:
  - DB=mysql DB_USER=root TEMP=/var/tmp/

before_script:
    - sudo sh -c "echo '127.0.0.1    ilee' >> /etc/hosts"
    - sudo apt-get install apache2
    - sudo a2enmod actions
    - sudo a2enmod rewrite
    - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars > /dev/null
    - cat test/config/default.apache2-vhost.conf | sed -e "s,PATH,`pwd`,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
    - sudo service apache2 restart
    - mysql -u root -e "CREATE USER 'kryn'@'localhost' IDENTIFIED BY ''"
    - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'kryn'@'localhost' WITH GRANT OPTION;"
    - mysql -e 'DROP DATABASE IF EXISTS test; CREATE DATABASE test;';

script:
  - sudo cat /etc/hosts;
  - sudo cat /etc/apache2/sites-available/default
  - sudo chown -R www-data .;
  - sudo chmod -R g-w .;
  - ls -al;
  - cd test;
  - sudo -u www-data phpunit Tests;

after_failure:
  - tail -n 50 /var/log/syslog
  - cat /var/log/apache2/*
  - cat /etc/apache2/sites-available/*;
  - cat /etc/apache2/sites-enabled/*;
